language: java

sudo: false

after_success:
- bash <(curl -s https://codecov.io/bash)
jdk:
- openjdk8
script: "mvn cobertura:cobertura"

notifications:
  email:
    recipients:
    - the.na4ig@gmail.com
    on_success: never
    on_failure: always

env:
  global:
   - CODECOV_TOKEN="d8c85250-acc9-4ae1-8c68-00eb52deb024"