language: java

cache:
  directories:
  - $HOME/.m2

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - the.na4ig@gmail.com
    on_success: never
    on_failure: always
